# Generated by Django 4.2.26 on 2025-11-27 10:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='نام انگلیسی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='لوگو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='نام انگلیسی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('category_type', models.CharField(choices=[('virtual', 'خدمات مجازی'), ('gaming', 'محصولات گیمینگ'), ('accessory', 'لوازم جانبی'), ('game_currency', 'ارز بازی')], default='virtual', max_length=20, verbose_name='نوع دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='کد محصول')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('product_type', models.CharField(choices=[('virtual', 'خدمات مجازی'), ('physical', 'محصول فیزیکی'), ('game_currency', 'ارز بازی')], default='virtual', max_length=20, verbose_name='نوع محصول')),
                ('delivery_type', models.CharField(choices=[('instant', 'تحویل فوری (خودکار)'), ('manual', 'تحویل دستی'), ('shipping', 'ارسال پستی')], default='instant', max_length=20, verbose_name='نوع تحویل')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='مشخصات فنی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('original_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت اصلی (قبل از تخفیف)')),
                ('cost_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تمام\u200cشده')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='آستانه هشدار موجودی')),
                ('track_stock', models.BooleanField(default=True, verbose_name='پیگیری موجودی')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن (گرم)')),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='{"length": 0, "width": 0, "height": 0}', verbose_name='ابعاد')),
                ('main_image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='تصویر اصلی')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_new', models.BooleanField(default=True, verbose_name='جدید')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='پرفروش')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='کد نوع')),
                ('attributes', models.JSONField(default=dict, verbose_name='ویژگی\u200cها')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('original_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت اصلی')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'انواع محصول',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سوال متداول محصول',
                'verbose_name_plural': 'سوالات متداول محصولات',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='GameCurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.PositiveIntegerField(verbose_name='حداقل مقدار')),
                ('max_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر مقدار')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت هر واحد (تومان)')),
                ('unit_name', models.CharField(default='واحد', help_text='مثال: UC، Diamond، V-Bucks', max_length=50, verbose_name='نام واحد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_rates', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نرخ ارز بازی',
                'verbose_name_plural': 'نرخ\u200cهای ارز بازی',
                'ordering': ['product', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='DigitalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='کد/اطلاعات')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='نام کاربری')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='رمز عبور')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='داده\u200cهای اضافی مانند PIN، کلید فعال\u200cسازی و...', verbose_name='اطلاعات اضافی')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('reserved', 'رزرو شده'), ('sold', 'فروخته شده'), ('expired', 'منقضی')], default='available', max_length=20, verbose_name='وضعیت')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ فروش')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('batch_id', models.CharField(blank=True, max_length=50, verbose_name='شناسه دسته')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_inventory', to='orders.orderitem', verbose_name='آیتم سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_inventory', to='products.product', verbose_name='محصول')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digital_inventory', to='products.productvariant', verbose_name='نوع محصول')),
            ],
            options={
                'verbose_name': 'موجودی دیجیتال',
                'verbose_name_plural': 'موجودی\u200cهای دیجیتال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بازدید')),
                ('view_count', models.PositiveIntegerField(default=1, verbose_name='تعداد بازدید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازدید اخیر',
                'verbose_name_plural': 'بازدیدهای اخیر',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='خرید تایید شده')),
                ('admin_response', models.TextField(blank=True, verbose_name='پاسخ مدیر')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر محصول',
                'verbose_name_plural': 'نظرات محصولات',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='products_pr_product_cea9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_2fee29_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalinventory',
            index=models.Index(fields=['product', 'status'], name='products_di_product_d44c47_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalinventory',
            index=models.Index(fields=['status'], name='products_di_status_367111_idx'),
        ),
    ]
