# Generated by Django 4.2.26 on 2025-12-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام برچسب')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('color', models.CharField(default='#6366f1', help_text='کد رنگ HEX مانند #6366f1', max_length=7, verbose_name='رنگ')),
                ('icon', models.CharField(blank=True, help_text='نام آیکون از Heroicons یا FontAwesome', max_length=50, verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='اولویت نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='products.product', verbose_name='محصول')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_items', to='products.productvariant', verbose_name='نوع محصول')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.wishlist', verbose_name='لیست علاقه\u200cمندی')),
            ],
            options={
                'verbose_name': 'آیتم علاقه\u200cمندی',
                'verbose_name_plural': 'آیتم\u200cهای علاقه\u200cمندی',
                'ordering': ['-created_at'],
                'unique_together': {('wishlist', 'product', 'variant')},
            },
        ),
    ]
