# Generated by Django 4.2.26 on 2025-12-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_products_ca_slug_da4386_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalProductProxy',
            fields=[
            ],
            options={
                'verbose_name': 'محصول فیزیکی',
                'verbose_name_plural': 'محصولات فیزیکی',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='VirtualProductProxy',
            fields=[
            ],
            options={
                'verbose_name': 'محصول مجازی',
                'verbose_name_plural': 'محصولات مجازی',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
