# Generated by Django 4.2.26 on 2025-12-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('accessory', 'محصولات جانبی'), ('gaming', 'محصولات گیمینگ'), ('virtual_service', 'خدمات مجازی'), ('mini_app', 'مینی اپ')], help_text='زیرنوع محصول را مشخص کنید تا در صفحات مجموعه\u200cبندی شود (مثال: محصولات جانبی، محصولات گیمینگ، خدمات مجازی، مینی اپ)', max_length=30, null=True, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='شناسه یکتا و قابل خواندن برای URL؛ معمولاً از نام انگلیسی تولید می\u200cشود. از حروف، اعداد و خط تیره استفاده کنید.', max_length=220, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='فرمت JSON برای مشخصات فنی. مثال: {"وزن": "200g", "رنگ": "مشکی", "cpu": "Intel i5"}. برای محصولات مجازی می\u200cتواند شامل اطلاعاتی مثل {"duration": "1 ماه", "platform": "PC"} باشد.', verbose_name='مشخصات فنی'),
        ),
    ]
