# Generated by Django 4.2.26 on 2025-12-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_sub_type_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_parent__1cafc9_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
