# Generated by Django 4.2.26 on 2025-12-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_category_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_form_fields',
            field=models.JSONField(blank=True, default=dict, help_text='فیلدهای سفارشی برای فرم خرید. مثال: [{"name": "phone", "label": "شماره تلفن", "type": "text", "required": true, "placeholder": "09123456789"}]', verbose_name='فیلدهای فرم سفارش'),
        ),
    ]
