# Generated by Django 4.2.26 on 2025-11-27 10:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='کلید نشست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('game_user_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه کاربری بازی')),
                ('currency_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار ارز بازی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم\u200cهای سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('tracking_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='کد پیگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('processing', 'در حال پردازش'), ('confirmed', 'تایید شده'), ('preparing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('refunded', 'مسترد شده'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_method', models.CharField(blank=True, choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی'), ('wallet', 'کیف پول'), ('mixed', 'ترکیبی')], max_length=20, verbose_name='روش پرداخت')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='جمع کل')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='تخفیف محصولات')),
                ('coupon_discount', models.PositiveIntegerField(default=0, verbose_name='تخفیف کوپن')),
                ('shipping_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('wallet_used', models.PositiveIntegerField(default=0, verbose_name='پرداخت از کیف پول')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='مبلغ نهایی')),
                ('amount_payable', models.PositiveIntegerField(default=0, help_text='مبلغ نهایی پس از کسر کیف پول', verbose_name='مبلغ قابل پرداخت')),
                ('shipping_data', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات ارسال')),
                ('customer_note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضای سفارش')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(max_length=20, verbose_name='وضعیت جدید')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت',
                'verbose_name_plural': 'تاریخچه وضعیت سفارش',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت واحد')),
                ('original_price', models.PositiveIntegerField(verbose_name='قیمت اصلی')),
                ('total_price', models.PositiveIntegerField(verbose_name='قیمت کل')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='تخفیف')),
                ('currency_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار ارز')),
                ('game_user_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه بازی')),
                ('delivery_data', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تحویل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
