# Generated by Django 4.2.26 on 2025-11-30 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'تاریخچه وضعیت', 'verbose_name_plural': 'تاریخچه وضعیت\u200cها'},
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییر توسط'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='note',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='وضعیت قبلی'),
        ),
    ]
