# Generated by Django 4.2.26 on 2025-12-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderstatushistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد تخفیف اعمال شده'),
        ),
    ]
