# Generated by Django 4.2.26 on 2025-12-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_applied_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='داده\u200cهای فیلدهای سفارشی برای خدمات مجازی', verbose_name='داده\u200cهای سفارشی سفارش'),
        ),
    ]
