# Generated by Django 4.2.26 on 2025-11-30 11:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(verbose_name='قیمت نهایی (تومان)')),
                ('session_link', models.URLField(blank=True, max_length=500, verbose_name='لینک جلسه')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='توضیحات کاربر')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('waiting', 'در انتظار شروع'), ('in_progress', 'در حال برگزاری'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('has_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'نوبت مشاوره',
                'verbose_name_plural': 'نوبت\u200cهای مشاوره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='مثال: روانشناس بالینی، وکیل پایه یک دادگستری', max_length=100, verbose_name='عنوان تخصصی')),
                ('bio', models.TextField(help_text='معرفی کوتاه (حداکثر ۵۰۰ کاراکتر)', verbose_name='درباره من')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='سال\u200cهای تجربه')),
                ('education', models.TextField(blank=True, help_text='مدارک تحصیلی (هر مدرک در یک خط)', verbose_name='تحصیلات')),
                ('certifications', models.TextField(blank=True, help_text='گواهینامه\u200cهای حرفه\u200cای', verbose_name='گواهینامه\u200cها')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='consulting/consultants/profiles/', verbose_name='تصویر پروفایل')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='consulting/consultants/covers/', verbose_name='تصویر کاور')),
                ('price_per_minute', models.PositiveIntegerField(default=5000, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='قیمت هر دقیقه (تومان)')),
                ('min_session_duration', models.PositiveSmallIntegerField(default=15, verbose_name='حداقل مدت جلسه (دقیقه)')),
                ('max_session_duration', models.PositiveSmallIntegerField(default=60, verbose_name='حداکثر مدت جلسه (دقیقه)')),
                ('is_active', models.BooleanField(default=True, help_text='آیا مشاور در حال حاضر فعال است؟', verbose_name='فعال')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('verification_status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('verified', 'تایید شده'), ('rejected', 'رد شده'), ('suspended', 'تعلیق شده')], default='pending', max_length=20, verbose_name='وضعیت تایید')),
                ('is_online', models.BooleanField(default=False, help_text='آیا مشاور الان آنلاین است؟', verbose_name='آنلاین')),
                ('is_available', models.BooleanField(default=True, help_text='آیا امکان رزرو وقت دارد؟', verbose_name='در دسترس')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='تعداد جلسات')),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='ساعات مشاوره')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نظرات')),
                ('national_id_image', models.ImageField(blank=True, null=True, upload_to='consulting/consultants/docs/', verbose_name='تصویر کارت ملی')),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='consulting/consultants/docs/', verbose_name='تصویر پروانه کار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('last_online_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین آنلاین')),
            ],
            options={
                'verbose_name': 'مشاور',
                'verbose_name_plural': 'مشاوران',
                'ordering': ['-rating', '-total_sessions'],
            },
        ),
        migrations.CreateModel(
            name='ConsultingCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, help_text='نام آیکون (مثلاً: psychology, gavel, account_balance)', max_length=50, verbose_name='آیکون')),
                ('image', models.ImageField(blank=True, null=True, upload_to='consulting/categories/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مشاوره',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مشاوره',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('duration', models.PositiveSmallIntegerField(default=30, verbose_name='مدت (دقیقه)')),
                ('status', models.CharField(choices=[('available', 'آزاد'), ('booked', 'رزرو شده'), ('blocked', 'بلاک شده')], default='available', max_length=20, verbose_name='وضعیت')),
                ('custom_price', models.PositiveIntegerField(blank=True, help_text='اگر خالی باشد از قیمت پیش\u200cفرض مشاور استفاده می\u200cشود', null=True, verbose_name='قیمت سفارشی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='consulting.consultant', verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'بازه زمانی',
                'verbose_name_plural': 'بازه\u200cهای زمانی',
                'ordering': ['date', 'start_time'],
                'unique_together': {('consultant', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ConsultantReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='نظر')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='consulting.appointment', verbose_name='نوبت')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='consulting.consultant', verbose_name='مشاور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulting_reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر مشاوره',
                'verbose_name_plural': 'نظرات مشاوره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='consultant',
            name='categories',
            field=models.ManyToManyField(related_name='consultants', to='consulting.consultingcategory', verbose_name='تخصص\u200cها'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='consulting.consultant', verbose_name='مشاور'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulting_appointments', to='payments.transaction', verbose_name='تراکنش پرداخت'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='consulting.timeslot', verbose_name='بازه زمانی'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
