# Generated by Django 4.2.26 on 2025-12-14 07:09

import apps.consulting.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consulting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_id', models.CharField(default=apps.consulting.models.generate_ticket_id, editable=False, help_text='شناسه 7 رقمی یکتا', max_length=7, unique=True, verbose_name='شماره تیکت')),
                ('subject', models.CharField(help_text='خلاصه کوتاه از مشکل یا سوال', max_length=200, verbose_name='موضوع')),
                ('initial_message', models.TextField(help_text='شرح کامل مشکل یا سوال', verbose_name='توضیحات اولیه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('in_progress', 'در حال بررسی'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=10, verbose_name='اولویت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد تیکت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('last_response_at', models.DateTimeField(blank=True, help_text='زمانی که آخرین پیام به تیکت اضافه شد', null=True, verbose_name='زمان آخرین پاسخ')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بسته شدن')),
                ('message_count', models.PositiveIntegerField(default=0, verbose_name='تعداد پیام\u200cها')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='پشتیبانی که به این تیکت اختصاص داده شده (برای کاربر نمایش داده نمی\u200cشود)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='پشتیبان تخصیص داده شده')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(help_text='فقط تصاویر با حجم حداکثر 5 مگابایت', upload_to='consulting/tickets/attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.consulting.models.validate_image_size], verbose_name='فایل')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم فایل (بایت)')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='نام اصلی فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
            ],
            options={
                'verbose_name': 'فایل ضمیمه',
                'verbose_name_plural': 'فایل\u200cهای ضمیمه',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='محتوای پیام', verbose_name='متن پیام')),
                ('is_staff_reply', models.BooleanField(default=False, help_text='آیا این پیام از طرف پشتیبان است؟ (برای کاربر به عنوان "پشتیبان" نمایش داده می\u200cشود)', verbose_name='پاسخ پشتیبان')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consulting.supportticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='consultantreview',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='consultantreview',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='consultantreview',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='consultant',
        ),
        migrations.AlterModelOptions(
            name='consultingcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'دسته\u200cبندی تیکت', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای تیکت'},
        ),
        migrations.AlterField(
            model_name='consultingcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='نام آیکون (مثلاً: support, help, question_answer)', max_length=50, verbose_name='آیکون'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Consultant',
        ),
        migrations.DeleteModel(
            name='ConsultantReview',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='consulting.ticketmessage', verbose_name='پیام'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='consulting.consultingcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['ticket_id'], name='consulting__ticket__fbdc43_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'status'], name='consulting__user_id_44e328_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority'], name='consulting__status_3576c3_idx'),
        ),
    ]
