# Generated by Django 4.2.26 on 2025-12-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0002_supportticket_ticketattachment_ticketmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], max_length=10, null=True, verbose_name='اولویت'),
        ),
    ]
