# Generated by Django 4.2.26 on 2025-12-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_birth_date_user_auth_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
    ]
