# Generated by Django 4.2.26 on 2025-12-14 05:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='content/articles/gallery/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, help_text='توضیح تصویر برای SEO و دسترسی\u200cپذیری', max_length=150, verbose_name='متن جایگزین')),
                ('caption', models.CharField(blank=True, help_text='توضیح کوتاه که زیر تصویر نمایش داده می\u200cشود', max_length=200, verbose_name='عنوان تصویر')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
            ],
            options={
                'verbose_name': 'تصویر مقاله',
                'verbose_name_plural': 'تصاویر مقالات',
                'ordering': ['article', 'order'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='like_count',
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='تگ\u200cهای مرتبط با این مقاله را انتخاب کنید. هر مقاله می\u200cتواند چند تگ داشته باشد.', related_name='articles', to='content.articletag', verbose_name='تگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='name',
            field=models.CharField(help_text='نام نمایشی تگ که در سایت نمایش داده می\u200cشود', max_length=50, unique=True, verbose_name='نام تگ'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='شناسه یکتا برای URL - به صورت خودکار از نام تگ تولید می\u200cشود', max_length=60, unique=True, verbose_name='نامک'),
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.article', verbose_name='مقاله'),
        ),
    ]
