# Generated by Django 4.2.26 on 2025-12-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('virtual', 'خدمات مجازی'), ('mini_game', 'مینی گیم'), ('gaming_products', 'محصولات گیمینگ'), ('accessories', 'لوازم جانبی')], max_length=50, unique=True, verbose_name='نوع خدمت')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='آیکون (اختیاری)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'توضیح خدمت',
                'verbose_name_plural': 'توضیحات خدمات',
            },
        ),
    ]
