# Generated by Django 4.2.26 on 2025-12-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, help_text='فقط نام کاربری را وارد کنید: مثلا minigame.shop', max_length=255, verbose_name='اینستاگرام (username)')),
                ('telegram', models.CharField(blank=True, help_text='فقط نام کاربری را وارد کنید: مثلا miniupir', max_length=255, verbose_name='تلگرام (username)')),
                ('youtube', models.CharField(blank=True, help_text='فقط نام کانال را وارد کنید: مثلا minigame_org', max_length=255, verbose_name='یوتیوب (channel name)')),
                ('whatsapp', models.CharField(blank=True, help_text='شماره تلفن یا لینک واتساپ', max_length=255, verbose_name='واتساپ (شماره یا لینک)')),
                ('twitter', models.CharField(blank=True, help_text='فقط نام کاربری را وارد کنید', max_length=255, verbose_name='توییتر/X (username)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'لینک شبکه اجتماعی',
                'verbose_name_plural': 'لینک\u200cهای شبکه\u200cهای اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='لینک کامل ویدیو یوتیوب را وارد کنید: مثلا https://www.youtube.com/watch?v=VIDEO_ID', max_length=500, verbose_name='لینک ویدیو یوتیوب')),
                ('title', models.CharField(help_text='عنوان نمایشی برای ویدیو', max_length=255, verbose_name='عنوان ویدیو')),
                ('description', models.TextField(blank=True, help_text='توضیح کوتاه درباره ویدیو', verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='ویدیو در صفحه اصلی نمایش داده شود؟', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'ویدیوی یوتیوب',
                'verbose_name_plural': 'ویدیوهای یوتیوب',
            },
        ),
    ]
