# Generated by Django 4.2.26 on 2025-11-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد کوپن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع تخفیف')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مقدار تخفیف')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, help_text='فقط برای تخفیف درصدی', max_digits=12, null=True, verbose_name='حداکثر تخفیف')),
                ('min_purchase', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='حداقل خرید')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد استفاده')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='حداکثر استفاده هر کاربر')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('valid_from', models.DateTimeField(verbose_name='معتبر از')),
                ('valid_until', models.DateTimeField(verbose_name='معتبر تا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('first_purchase_only', models.BooleanField(default=False, verbose_name='فقط اولین خرید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کوپن',
                'verbose_name_plural': 'کوپن\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ تخفیف')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon', verbose_name='کوپن')),
            ],
            options={
                'verbose_name': 'استفاده از کوپن',
                'verbose_name_plural': 'استفاده\u200cهای کوپن',
                'ordering': ['-used_at'],
            },
        ),
    ]
