# Generated by Django 4.2.26 on 2025-11-27 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='allowed_categories',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='products.category', verbose_name='دسته\u200cبندی\u200cهای مجاز'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='allowed_products',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='products.product', verbose_name='محصولات مجاز'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_coupons', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز'),
        ),
    ]
