# Generated by Django 4.2.26 on 2025-11-27 10:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام درگاه')),
                ('gateway_type', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی')], max_length=20, unique=True, verbose_name='نوع درگاه')),
                ('merchant_id', models.CharField(help_text='Merchant ID یا API Key', max_length=100, verbose_name='کد پذیرنده')),
                ('api_key', models.CharField(blank=True, help_text='در صورت نیاز درگاه', max_length=200, verbose_name='کلید API')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_sandbox', models.BooleanField(default=True, help_text='برای تست درگاه فعال کنید', verbose_name='حالت تست')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='درگاه با اولویت بالاتر ابتدا نمایش داده می\u200cشود', verbose_name='اولویت')),
                ('min_amount', models.PositiveIntegerField(default=1000, verbose_name='حداقل مبلغ (تومان)')),
                ('max_amount', models.PositiveIntegerField(default=50000000, verbose_name='حداکثر مبلغ (تومان)')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='تعداد تراکنش')),
                ('successful_transactions', models.PositiveIntegerField(default=0, verbose_name='تراکنش موفق')),
                ('total_amount', models.BigIntegerField(default=0, verbose_name='مجموع مبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'درگاه پرداخت',
                'verbose_name_plural': 'درگاه\u200cهای پرداخت',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه تراکنش')),
                ('tracking_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='کد پیگیری')),
                ('transaction_type', models.CharField(choices=[('order', 'پرداخت سفارش'), ('topup', 'شارژ کیف پول'), ('consultation', 'پرداخت مشاوره')], default='order', max_length=20, verbose_name='نوع تراکنش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('refunded', 'مسترد شده'), ('expired', 'منقضی شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000)], verbose_name='مبلغ (تومان)')),
                ('amount_rial', models.PositiveIntegerField(help_text='مبلغ به ریال برای ارسال به درگاه', verbose_name='مبلغ (ریال)')),
                ('authority', models.CharField(blank=True, db_index=True, help_text='کد دریافتی از درگاه برای هدایت کاربر', max_length=100, verbose_name='کد Authority')),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='شماره پیگیری بانکی پس از پرداخت موفق', max_length=100, verbose_name='شماره مرجع')),
                ('gateway_request', models.JSONField(blank=True, default=dict, verbose_name='درخواست به درگاه')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='پاسخ درگاه')),
                ('verify_response', models.JSONField(blank=True, default=dict, verbose_name='پاسخ تایید')),
                ('card_number', models.CharField(blank=True, help_text='به صورت ماسک شده: 6037-****-****-1234', max_length=20, verbose_name='شماره کارت')),
                ('card_hash', models.CharField(blank=True, max_length=100, verbose_name='هش کارت')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('error_code', models.CharField(blank=True, max_length=20, verbose_name='کد خطا')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymentgateway', verbose_name='درگاه')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_tr_user_id_b99a80_idx'), models.Index(fields=['status', 'created_at'], name='payments_tr_status_e3597b_idx'), models.Index(fields=['gateway', 'status'], name='payments_tr_gateway_defd87_idx')],
            },
        ),
    ]
