# Generated by Django 4.2.26 on 2025-11-30 11:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_orderstatushistory_options_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='موجودی (تومان)')),
                ('gift_balance', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='اعتبار هدیه (تومان)')),
                ('total_deposited', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='مجموع شارژ')),
                ('total_spent', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='مجموع خرج شده')),
                ('is_locked', models.BooleanField(default=False, verbose_name='قفل شده')),
                ('lock_reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل قفل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('transaction_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='شناسه تراکنش')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'شارژ'), ('withdraw', 'برداشت'), ('purchase', 'خرید'), ('refund', 'استرداد'), ('gift', 'هدیه'), ('cashback', 'کش\u200cبک'), ('admin_adjust', 'تنظیم ادمین'), ('transfer_in', 'انتقال دریافتی'), ('transfer_out', 'انتقال ارسالی')], max_length=20, verbose_name='نوع تراکنش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('reversed', 'برگشت خورده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('is_gift_credit', models.BooleanField(default=False, verbose_name='اعتبار هدیه')),
                ('balance_before', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='موجودی قبل')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='موجودی بعد')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order', verbose_name='سفارش')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='payments.transaction', verbose_name='تراکنش پرداخت')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletDepositRequest',
            fields=[
                ('authority', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد Authority زرین\u200cپال')),
                ('ref_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری')),
                ('gateway', models.CharField(default='zarinpal', max_length=20, verbose_name='درگاه پرداخت')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10000'))], verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('expired', 'منقضی')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_deposit', to='payments.transaction', verbose_name='تراکنش پرداخت')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requests', to='wallet.wallet', verbose_name='کیف پول')),
                ('wallet_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_request', to='wallet.wallettransaction', verbose_name='تراکنش کیف پول')),
            ],
            options={
                'verbose_name': 'درخواست شارژ',
                'verbose_name_plural': 'درخواست\u200cهای شارژ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_wall_wallet__ccf672_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type'], name='wallet_wall_transac_2c0a43_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='wallet_wall_status_66d39d_idx'),
        ),
    ]
