# Generated by Django 4.2.26 on 2025-12-15 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=255, verbose_name='هش رمز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='تلاش\u200cهای ناموفق')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='قفل تا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین احراز هویت')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'رمز کیف پول',
                'verbose_name_plural': 'رمزهای کیف پول',
            },
        ),
    ]
